//
//  Colors.swift
//  whatsAppClone
//
//  Created by Rafael on 14/10/24.
//

import UIKit

struct Colors {

    // MARK: - Border Colors
    static let borderAvatar = UIColor(named: "brd-avatar")
    static let borderCheckRadio = UIColor(named: "brd-check-radio")
    static let borderCheckbox = UIColor(named: "brd-checkbox")
    static let borderCtaSeparator = UIColor(named: "brd-cta-separator")
    static let borderInputChat = UIColor(named: "brd-input-chat")
    static let borderPanel = UIColor(named: "brd-panel")
    static let borderProduct = UIColor(named: "brd-product")
    static let borderQuote = UIColor(named: "brd-quote")
    static let borderReaction = UIColor(named: "brd-reaction")
    static let borderSeparator = UIColor(named: "brd-separator")
    static let borderUnread = UIColor(named: "brd-unread")

    // MARK: - Icons Colors
    static let iconActive = UIColor(named: "icon-active")
    static let iconCheckBaloon = UIColor(named: "icon-check-baloon")
    static let iconCheck = UIColor(named: "icon-check")
    static let iconColorCamera = UIColor(named: "icon-color-camera")
    static let iconColorContact = UIColor(named: "icon-color-contact")
    static let iconColorDocument = UIColor(named: "icon-color-document")
    static let iconColorLocation = UIColor(named: "icon-color-location")
    static let iconColorPhoto = UIColor(named: "icon-color-photo")
    static let iconColorPoll = UIColor(named: "icon-color-poll")
    static let iconDanger = UIColor(named: "icon-danger")
    static let iconDisabled = UIColor(named: "icon-disabled")
    static let iconForw = UIColor(named: "icon-forw")
    static let iconInvert = UIColor(named: "icon-invert")
    static let iconPrimary = UIColor(named: "icon-primary")
    static let iconProduct = UIColor(named: "icon-product")
    static let iconSecondaryAlpha = UIColor(named: "icon-secondary-alpha")
    static let iconSecondary = UIColor(named: "icon-secondary")
    static let iconSideOptionGreen = UIColor(named: "icon-side-option-green")
    static let iconSideOptionGrey = UIColor(named: "icon-side-option-grey")
    static let iconTabBarSelected = UIColor(named: "icon-tabbar-selected")
    static let iconTabBar = UIColor(named: "icon-tabbar")
    static let iconTertiary = UIColor(named: "icon-tertiary")

    // MARK: - Suface Colors
    static let surfaceAlert = UIColor(named: "surface-alert")
    static let surfaceAttachment = UIColor(named: "surface-attachment")
    static let surfaceBaloonFriend = UIColor(named: "surface-baloon-friend")
    static let surfaceBaloonMe = UIColor(named: "surface-baloon-me")
    static let surfaceCallIcon = UIColor(named: "surface-calls-icon")
    static let surfaceCalls = UIColor(named: "surface-calls")
    static let surfaceChat = UIColor(named: "surface-chat")
    static let surfaceCtaCircular = UIColor(named: "surface-cta-circular")
    static let surfaceCtaFiltersActive = UIColor(named: "surface-cta-filters-active")
    static let surfaceCtaFiltersDisabled = UIColor(named: "surface-cta-filters-disabled")
    static let surfaceCtaFilters = UIColor(named: "surface-cta-filters")
    static let surfaceCtaOptions = UIColor(named: "surface-cta-options")
    static let surfaceDate = UIColor(named: "surface-date")
    static let surfaceForw = UIColor(named: "surface-forw")
    static let surfaceInputChat = UIColor(named: "surface-input-chat")
    static let surfaceInputUpdate = UIColor(named: "surface-input-update")
    static let surfaceInvert = UIColor(named: "surface-invert")
    static let surfaceOptions = UIColor(named: "surface-options")
    static let surfacePanelBlur = UIColor(named: "surface-panel-blur")
    static let surfacePanel = UIColor(named: "surface-panel")
    static let surfacePrimary = UIColor(named: "surface-primary")
    static let surfaceProduct = UIColor(named: "surface-product")
    static let surfaceProgressPollTrack = UIColor(named: "surface-progress-poll-track")
    static let surfaceProgressTrack = UIColor(named: "surface-progress-track")
    static let surfaceProgress = UIColor(named: "surface-progress")
    static let surfaceReaction = UIColor(named: "surface-reaction")
    static let surfaceSearchChat = UIColor(named: "surface-search-chat")
    static let surfaceSearch = UIColor(named: "surface-search")
    static let surfaceSecondary = UIColor(named: "surface-secondary")
    static let surfaceSegmentedSelected = UIColor(named: "surface-segmented-selected")
    static let surfaceSegmented = UIColor(named: "surface-segmented")
    static let surfaceSelectionlist = UIColor(named: "surface-selection-list")
    static let surfaceShadowBaloon = UIColor(named: "surface-shadow-baloon")
    static let surfaceSideOptionGreen = UIColor(named: "surface-side-option-green")
    static let surfaceSideOptionGrey = UIColor(named: "surface-side-option-grey")
    static let surfaceSoundOff = UIColor(named: "surface-sound-off")
    static let surfaceSoundOn = UIColor(named: "surface-sound-on")
    static let surfaceSpeed = UIColor(named: "surface-speed")
    static let surfaceSwitchOff = UIColor(named: "surface-switch-off")
    static let surfaceUnread = UIColor(named: "surface-unread")

    // MARK: - Text Colors
    static let textAlert = UIColor(named: "txt-alert")
    static let textCtaDisabled = UIColor(named: "txt-cta-disabled")
    static let textCtaFiltersActive = UIColor(named: "txt-cta-filters-active")
    static let textCtaFilters = UIColor(named: "txt-cta-filters")
    static let textDanger = UIColor(named: "txt-danger")
    static let textInvert = UIColor(named: "txt-invert")
    static let textLink = UIColor(named: "txt-link")
    static let textPrimary = UIColor(named: "txt-primary")
    static let textProduct = UIColor(named: "txt-product")
    static let textQuoteTit = UIColor(named: "txt-quote-tit")
    static let textQuoteTxt = UIColor(named: "txt-quote-txt")
    static let textSecondaryAlpha = UIColor(named: "txt-secondary-alpha")
    static let textSecondary = UIColor(named: "txt-secondary")
    static let textSideOptionGreen = UIColor(named: "txt-side-option-green")
    static let textSideOptionGrey = UIColor(named: "txt-side-option-grey")
    static let textTabBarSelected = UIColor(named: "txt-tabbar-selected")
    static let textTabBar = UIColor(named: "txt-tabbar")

}
